### PR TITLE
Feature/drop php7.2

### PR DESCRIPTION
**Pull request by t0mmy742**
Drop PHP 7.2 from this repo
Also fixed tests error

### CODE REVIEW

**Comment by l0gicgate** [comment]
The CI errors are caused by downstream libraries by the looks of it 🤔

**Comment by t0mmy742** [comment]
Yes, some PSR-7 providers are not totally PSR-7 compliant.

**Comment by l0gicgate** [comment]
I'm a bit confused as to where this status comes from on the psr7 integration test repo:
screenshot

Laminas clearly doesn't pass the test:
screenshot2

**Comment by l0gicgate** [comment]
Also, it seems that static analysis and code coverage is not running 🤔

**Comment by t0mmy742** [comment]
`php-http/psr7-integration-tests` repo is not running tests anymore. They were on Travis-CI but "building on travis-ci.org is ceased".

**Comment by t0mmy742** [comment]
> 
> 
> Also, it seems that coveralls run on PHP 8 but the results are not being uploaded.

I think following jobs are not running if one already failed.

**Comment by l0gicgate** [comment]
Opened an issue on Laminas repo:
https://github.com/laminas/laminas-diactoros/issues/74

**Review by l0gicgate — APPROVED** [review]

**Pull request merged**
